### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by alph486** [joscha/play-authenticate#242]
I know its rather trivial, but it'd be nice if on the readme the maven coordinates could be posted in getting started and/or any other necessary configurations. There are a lot of great samples (thank you!) but nothing tops some front page material :)

Let me know if i missed something too.

Thanks!

**Comment by joscha** [comment]
@alph486 do you remember what exactly would have helped you? Usually the samples should be just fine to get started - the [maven coordintates](https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/build.sbt#L12) are included in that...

**Comment by alph486** [comment]
Hey joscha, maybe I'll send you a little pull request to illustrate. It's nothing big just a little convenience. :-) 

Thanks
KK

**Comment by alph486** [comment]
The aforementioned Pull Request is what I was referring to. I realize that's kind of academic, but good if you're looking for a quick reference to a dependency; analogous to seeing 'npm install <blah>' or pip 'install blah' on the front page of Javascript or Python dependencies. Anyway, up to you thanks for the convo.

**Comment by joscha** [comment]
added, thank you.
