### ISSUE TITLE
Local Development of Play! Authenticate

### ISSUE THREAD

**Issue by oexza** [joscha/play-authenticate#255]
how do i work with a local development of play-auth? i want to edit play-auth source code with eclipse ide

**Comment by joscha** [comment]
Hi @oexza - there are some comments, [https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/build.sbt#L11] and [here](https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/project/plugins.sbt#L15-L19). Just comment/uncomment to enable local development.
