### ISSUE TITLE
Migrating to play 2.4

### ISSUE THREAD

**Issue by umbreak** [joscha/play-authenticate#256]
Play 2.4 is out. Does the latest version support it? And dependency injection?

The documentation does not point out anything about it.

I've seen you were working on it in https://github.com/joscha/play-authenticate/pull/249

**Comment by tuanvm** [comment]
Please update status of this open issue? Mailer Plugin is changed in Play 2.4, need an update for it.

**Comment by joscha** [comment]
@tuanvm as far as I know @mkurz is working on it today, however feel free to join in.

**Comment by mkurz** [comment]
@umbreak @tuanvm [`0.7.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/feth/play-authenticate_2.11/0.7.0-SNAPSHOT/) with Play 2.4 support is available on sonatype now!
