### ISSUE TITLE
Provide DI Authenticate controller

### ISSUE THREAD

**Issue by mkurz** [joscha/play-authenticate#267]
See https://groups.google.com/forum/?fromgroups#!topic/play-framework/IrMKSik-kw8

@joscha Basically I would copy [Authenticate.java](https://github.com/joscha/play-authenticate/blob/5d0b8c6dd915ffe0ac4177f1fd2c982a84e18461/code/app/com/feth/play/module/pa/controllers/Authenticate.java), name it `AuthenticateDI.java` and remove the static keyword. What do you think?

**Comment by joscha** [comment]
yes, that seems reasonable. Amazing you picked that up!

**Comment by mkurz** [comment]
Fixed via #268
