### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by lennartdiedrich** [joscha/play-authenticate#269]
Hi, can you estimate when the 0.7.0 will be available at Maven?

**Comment by joscha** [comment]
have you tried the snapshot? Does it work for you?

**Comment by lennartdiedrich** [comment]
Hi joscha, 
no, i have not, but will do it now. Do you hesitate publishing because of missing beta tests for this version?

**Comment by joscha** [comment]
I just think the more people give the snapshot a try, the more likely a
release will be a good release. Especially on a .zero version :)
Am 05.07.2015 14:10 schrieb "Lennart Diedrich" <notifications@github.com>:

**Comment by lennartdiedrich** [comment]
Sorry for the late response. I had no problems updating to the snapshots. Works like a charm ;)

**Comment by ronaldwidha** [comment]
took me a while to work what to put on build.sbt out, so sharing it here:

    libraryDependencies ++= Seq(
      "com.feth" %%  "play-authenticate" % "0.7.0-SNAPSHOT" // authentication
    )

    resolvers ++= Seq(
      "play-authenticate (snapshot)" at "https://oss.sonatype.org/content/repositories/snapshots/"
    )

**Comment by joaoferreira89** [comment]
Hi, 
I'm using the 0.7.0 SNAPSHOT version, that is hosted on https://oss.sonatype.org/content/repositories/snapshots/, but this repository is very slow and sometimes is down.
Can you please host it on a Maven repository?

Best regards

**Comment by joscha** [comment]
I think it is about time for a 0.7.0 release, yes

**Comment by oexza** [comment]
yeah @joscha considering that it has worked smoothly so far, but maybe it should be migrated away from play's deprecated plugin system to the DI module system before a release.

**Comment by mkurz** [comment]
I think its ok for now to release 0.7.0 which targets Play 2.4 to finally get a stable release out which works for Play 2.4.
Then we could make the switch to the DI module system to target upcoming Play 2.5.
Just my 2 cents.

**Comment by raunak** [comment]
Could someone comment on how much work it would be to update the module to support the new DI module?

**Comment by joscha** [comment]
Release is here: https://oss.sonatype.org/content/repositories/releases/com/feth/play-authenticate_2.11/0.7.0/
