### ISSUE TITLE
Exception running example simple-oauth

### ISSUE THREAD

**Issue by bravegag** [joscha/play-authenticate#278]
I am looking for a linkedin example and trying to see whether the simple-oauth application has it and works I get the following exception.

Unexpected exception

RuntimeException: Provider 'google' missing needed setting 'clientId'
No source available, here is the exception stack trace:

->java.lang.RuntimeException: Provider 'google' missing needed setting 'clientId'

     com.feth.play.module.pa.providers.AuthProvider.onStart(AuthProvider.java:74)

     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)

     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)

     scala.collection.Iterator$class.foreach(Iterator.scala:750)

     scala.collection.AbstractIterator.foreach(Iterator.scala:1202)

     scala.collection.IterableLike$class.foreach(IterableLike.scala:72)

     play.api.Plugins.foreach(Plugins.scala:57)

     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)

     play.api.Play$$anonfun$start$1.apply(Play.scala:91)

     play.api.Play$$anonfun$start$1.apply(Play.scala:91)

     play.utils.Threads$.withContextClassLoader(Threads.scala:21)

     play.api.Play$.start(Play.scala:90)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)

     scala.Option.map(Option.scala:146)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)

     scala.util.Success.flatMap(Try.scala:230)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)

     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by joscha** [comment]
For each provider you want to use (Google is one example), you need to
define your clientId and clientSecret in the config file. Have a look at
the .conf file and it tells you where you can get them!

**Comment by bravegag** [comment]
Thank you! btw is this the application simple-oauth the one deployed in as live demo in heroku?

**Comment by joscha** [comment]
No, that's the usage one (well, an old version of it)

**Comment by bravegag** [comment]
ahh but the usage one in master doesn't have the linkedin example I am after ... :( do you have a code example specifically for linkedin? or maybe the old version how to do it?

**Comment by joscha** [comment]
You just need to enable the plugin, that's it. You can either see how that
works in the sample app or read the .md file about it.

**Comment by bravegag** [comment]
But there must be specific code to do when I want to login to my application via Linkedin and I wanted to find an example ... the usage example doesn't include linkedin ... I checked already. Thanks for your support. I just need a linkedin example that's all.

**Comment by joscha** [comment]
All providers work the same way. It makes no difference whether it is
twitter, LinkedIn or Google. You add the plugin, add the credentials, done.

**Comment by bravegag** [comment]
Is there a sample app usage written in Scala rather than Java?

**Comment by joscha** [comment]
You can find one in #212.
I am going to close this issue now, as the initial problem is resolved.
