### ISSUE TITLE
What version of Ebean is used in the sample projects?

### ISSUE THREAD

**Issue by bravegag** [joscha/play-authenticate#281]
This is more a general support question but I can't see  what version of Ebean is being used e.g.
https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/build.sbt

       lazy val root = project.in(file("."))
            .enablePlugins(PlayJava, PlayEbean)
            .settings(
            libraryDependencies ++= appDependencies
       )

I see the plugin PlayEbean is used but which version of that plugin and for that matter what Ebean version is being used?

**Comment by adis-me** [comment]
I think you should be able to see the **sbt-play-ebean** version inside `project/plugins.sbt`.
See also the project https://github.com/playframework/play-ebean
