### ISSUE TITLE
Secure an action

### ISSUE THREAD

**Issue by raunak** [joscha/play-authenticate#285]
How do I secure an action without using Deadbolt? 
By secure, I mean, the user must be authenticated prior to be able to access an action.

**Comment by oexza** [comment]
in the simple oauth sample this controller https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/app/controllers/Restricted.java is being secured by this https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/app/controllers/Secured.java which is just implementing play! framework authentication mechanism, no extra nothing but i dont see why you wouldn't wanna use deadbolt, deadbolt is raw power!

**Comment by raunak** [comment]
How does that then call the various methods in the userservice implementation?

**Comment by raunak** [comment]
As you pointed out @oexza, securing action using Security.Authenticator works fine. 
The issue was, I'm trying to use the new DI mechanism instead of plugins, which prevented the onStart method from being called for the plugins.
