### ISSUE TITLE
Play Framework 2.5 upgrade

### ISSUE THREAD

**Issue by joaoferreira89** [joscha/play-authenticate#295]
Hi @joscha ,

Are you planning an update to support the new version of the play framework?
On the changelog, it says that the plugins API has been removed on this version, and the play-authenticate relies on this.
https://playframework.com/documentation/2.5.x/Migration25#Removed-Plugins-API

Best regards,
João Ferreira

**Comment by pdolega** [comment]
Hey @joaoferreira89 @joscha 

I started working on this during the weekend - here is WIP PR https://github.com/joscha/play-authenticate/pull/298

I am going to test it in next few days and probably could have it ready before the end of the week (assuming @joscha won't have any *very serious* complaints).

**Comment by joscha** [comment]
closed via f41f75b

**Comment by slimandslam** [comment]
Is version 0.7.1 still supported ??   I'm getting this:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.feth#play-authenticate_2.11;0.7.1-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
