### ISSUE TITLE
Version 0.7.1 no longer supported??!!

### ISSUE THREAD

**Issue by slimandslam** [joscha/play-authenticate#302]
I can no longer compile my (previously working) Play app (Play v2.4.6) because 
"0.7.1-SNAPSHOT" of play-authenticate cannot be found. Did it get pulled from the SBT repo?

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.feth#play-authenticate_2.11;0.7.1-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by slimandslam** [comment]
you have to use

**Comment by joscha** [comment]
Nothing was removed, however I recommend using `0.7.1` instead of the snapshot.
