### ISSUE TITLE
What provider do I need for a email/password authentication?

### ISSUE THREAD

**Issue by nem25** [joscha/play-authenticate#304]
Hi,

Sorry I know this is not really an issue but the [readme](https://github.com/joscha/play-authenticate/blob/master/samples/java/Getting%20Started.md) only has info about Google Authenticator.

I just want a simple email and password login where my users are stored in a mongo db. I don't want google or any social media authentication.

The example code has a few different providers and AuthUsers so I'm not really sure which one I need.

Thanks!

**Comment by joscha** [comment]
You need the one called `password`.

**Comment by nem25** [comment]
So any of the providers in here - https://github.com/joscha/play-authenticate/tree/master/code/app/com/feth/play/module/pa/providers/password ?

**Comment by joscha** [comment]
Yes, have a look at the sample: https://github.com/joscha/play-authenticate/blob/4b3fe4965713f218df5950eedb555b89f53f0519/samples/java/play-authenticate-usage/app/module/MyModule.java#L39

**Comment by nem25** [comment]
Ah ok so this one - https://github.com/joscha/play-authenticate/blob/4b3fe4965713f218df5950eedb555b89f53f0519/samples/java/play-authenticate-usage/app/providers/MyUsernamePasswordAuthProvider.java
Awesome thanks so much for your help!

**Comment by joscha** [comment]
Yep, you basically register a provider with a given key. You can write your own, use one of the ones that come with play-authenticate or extend from one of them.
