### ISSUE TITLE
error when try Sample : play-authenticate-simple-oauth

### ISSUE THREAD

**Issue by HannahJSwystun** [joscha/play-authenticate#308]
![sans titre](https://cloud.githubusercontent.com/assets/20491664/17013462/3eb794b2-4f0e-11e6-98a5-07b7ea32e1fa.png)

**Comment by joscha** [comment]
The OAuth examples require a clientId and a clientSecret. Please have a
look at the config files, there are links in there that tell you where to
get them.

Cheers,
Joscha

**Comment by HannahJSwystun** [comment]
Hi,

Why did you closed the issue!!!
Firstable, I run the app then I apply Script for SQL ...and get this error and I know I do not know how to get the informations clientID and clientSecret..
please help

**Comment by joscha** [comment]
https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/conf/play-authenticate/mine.conf
