### ISSUE TITLE
Maven Central does not have version 0.8.x

### ISSUE THREAD

**Issue by AkbarTheGreat** [joscha/play-authenticate#310]
The documentation in the README even goes so far as to have snippets to get that from maven-central, but the newest is 0.7.1.

**Comment by leccyril** [comment]
same for me i'va update to play 2.5 but version availabe on maven repo 0.7.1

**Comment by gmsa** [comment]
You need to add the snapshots repository to build.sbt:

`resolvers ++= Seq("Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots")`

**Comment by leccyril** [comment]
thank you

**Comment by dwhu** [comment]
Can you please still update the Maven Central?

**Comment by joscha** [comment]
Should appear here in a few minutes: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.feth%22%20AND%20a%3A%22play-authenticate_2.11%22
