### ISSUE TITLE
Last commit  version 0.8.2-SNAPSHOT not working

### ISSUE THREAD

**Issue by GelukkigTurtle** [joscha/play-authenticate#322]
Hello, i am working with this library, everything was ok until now. i cannot run my play project.  SBT resolution show me:

**bt.ResolveException: unresolved dependency: com.feth#play-authenticate_2.11;0.8.2-SNAPSHOT: not found**

Can you help me with this problem? Sorry if i am doing something bad. and thank you in advance!

**Comment by Mule52** [comment]
I am using 0.8.1 and I just received similar errors to the original poster. I have not even upgraded to 0.8.2.

com.feth#play-authenticate_2.11;0.8.1-SNAPSHOT: not found
com.feth#play-easymail_2.11;0.8.1-SNAPSHOT: not found

unresolved dependency: com.feth#play-authenticate_2.11;0.8.1-SNAPSHOT: not found
unresolved dependency: com.feth#play-easymail_2.11;0.8.1-SNAPSHOT: not found

Thanks for any help.

**Comment by joscha** [comment]
Can you guys try and use the `0.8.1` version (no `-SNAPSHOT`) directly and
let me know if that works? I didn't release a 0.8.2-SNAPSHOT, because there
are no changes, yet.

**Comment by Mule52** [comment]
These are the only two working for me.

"com.feth" %% "play-authenticate" % "0.8.1",
"com.feth" %% "play-easymail" % "0.8.1",

Thanks.

**Comment by GelukkigTurtle** [comment]
Thank  you guys! problem FIXED

**Comment by 030** [comment]
Should this not be changed in the build.sbt? At the moment when sbt run is done the error still occurs:

```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.feth#play-authenticate_2.11;0.8.2-SNAPSHOT: not found
[error] Total time: 19 s, completed Jan 19, 2017 8:56:36 AM
```

What about changing 0.8.2-snapshot to 0.8.1?
