### ISSUE TITLE
Samples not working!

### ISSUE THREAD

**Issue by placebocurejava** [joscha/play-authenticate#325]
Hi,

When I launched on of the two samples i got the same error : 
"com.feth" %% "play-authenticate" % "0.8.2-SNAPSHOT"2.11 not found !!!

SBT clean run...

any idea ?

**Comment by joscha** [comment]
You need to locally publish the library code or uncomment the lines that
are preceded with // uncomment for local development.

**Comment by placebocurejava** [comment]
Thank you so much for reply,

My goal was to see how deadbolt was integrated in an other
sample....anyways really thanks :)
