### ISSUE TITLE
google icon does not appear

### ISSUE THREAD

**Issue by 030** [joscha/play-authenticate#326]
when sbt run is executed in samples/java/play-authenticate-usage then a webpage is shown but there is no google icon. How to let it appear?

**Comment by joscha** [comment]
You need to enable the Google oauth adapter in the plugin config and add
the key and secret to the conf file. You can have a look at the simple
example on how to do that.

**Comment by 030** [comment]
I habe entered the client and id in  play-authenticate/samples/java/play-authenticate-usage/conf/play-authenticate/mine.conf but the icon will not appear

**Comment by joscha** [comment]
did you also enable the google plugin? See https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-usage/app/module/MyModule.java

**Comment by 030** [comment]
```
[error] /tmp/play-authenticate/samples/java/play-authenticate-usage/app/module/MyModule.java:36: cannot find symbol
[error]   symbol:   class GoogleAuthProvider
[error]   location: class module.MyModule
[error] 		bind(GoogleAuthProvider.class).asEagerSingleton();
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] application -
```

**Comment by 030** [comment]
I forgot to import 
```
import com.feth.play.module.pa.providers.oauth2.google.GoogleAuthProvider;
```

**Comment by 030** [comment]
Current issue:

```
Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:9000/authenticate/google, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/140904023443-r4rf6hdmo8b6onuf31qrvsot3a7ia008.apps.googleusercontent.com?project=140904023443 to update the authorized redirect URIs.
```

**Comment by 030** [comment]
After adding http://localhost:9000/authenticate/google in the console it works to login with my account. Thank you!
