### ISSUE TITLE
Sample application's Exception.(sbt.ResolveException)

### ISSUE THREAD

**Issue by KazuyaTomita** [joscha/play-authenticate#327]
When I try to launch the sample application, I saw this error:
`[error] (*:update) sbt.ResolveException: unresolved dependency: com.feth#play-authenticate_2.11;0.8.2-SNAPSHOT: not found`

What should I do?   I think the first thing I have to do is find out which version I am using, but in play-authentication, that is hind because in `plugin.sbt`, the code is using `System.getProperty()` method, so now I have lost my way for this problem.

Moreover, I can't open the app on Heroku, neither.

**Comment by Shenker93** [comment]
Don't know about snapshots, however, you can use "com.feth" %% "play-authenticate" % "0.8.1" (from maven-central) in build.sbt file instead of 0.8.2-SNAPSHOT,

**Comment by KazuyaTomita** [comment]
@Shenker93 
Thank you for your reply. Do you mean I add the line ` "com.feth" %% "play-authenticate" % "0.8.1"` in libraryDependencies in `build.sbt`?    But still it doesn't work.   And I also tried to add `"com.feth"  %% "play-authenticate_2.11" % "0.8.2-SNAPSHOT"` in libraryDependencies.   And it still complains `com.feth#play-authenticate_2.11;0.8.2-SNAPSHOT: not found`.

**Comment by Shenker93** [comment]
@KazuyaTomita 
Yes, if you've tried samples/java/play-authenticate-usage, this will fix the problem.
Just tried on my machine and it works. 

`val appDependencies = Seq(
  "be.objectify"  %% "deadbolt-java"     % "2.5.0",
  // Comment the next line for local development of the Play Authentication core:
  "com.feth"      %% "play-authenticate" % "0.8.1",
  "org.postgresql"    %  "postgresql"        % "9.4-1201-jdbc41",
  cache,
  javaWs,
  javaJdbc,
  "org.webjars" % "bootstrap" % "3.2.0",
  "org.easytesting" % "fest-assert" % "1.4" % "test",
  "org.seleniumhq.selenium" % "selenium-java" % "2.52.0" % "test"
)`

If you still have the same problem, try to execute `sbt clean` command before launching maybe.

**Comment by joscha** [comment]
Sorry about that, fixed via b3d1e7b
