### ISSUE TITLE
How to use this library in an existing Play?

### ISSUE THREAD

**Issue by 030** [joscha/play-authenticate#331]
I have added the following to the build.sbt

`"com.feth" %% "play-authenticate" % "0.8.1"`

added `<a href="@com.feth.play.module.pa.controllers.routes.Authenticate.logout">Logout</a>` to my `app/views/index.scala.html`

when the app is run it results in:

```
[error] /path/to/play/app/views/index.scala.html:9: object routes is not a member of package com.feth.play.module.pa.controllers
[error] 		<a href="@com.feth.play.module.pa.controllers.routes.Authenticate.logout">Logout</a>
[error]
```

How to add the library so that I do not have to copy all the code?

I have checked https://github.com/joscha/play-authenticate/tree/master/samples/java/play-authenticate-simple-oauth

My question is whether I should copy all the java code that resides in the app dir or could this be included using the build.sbt?

**Comment by nagytech** [comment]
No, you don't need to copy all of the code in the app directory.  But, adding the dependency only gets you so far.

At minimum, you will need your own [AbstractUserService](https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/app/service/MyUserService.java) implementation and a [Resolver](https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/app/service/MyResolver.java) implementation.  You will also need to bind them in your default module (if you have one), or create a [new one](https://github.com/joscha/play-authenticate/blob/master/samples/java/play-authenticate-simple-oauth/app/module/SimpleOAuthModule.java).

**Comment by 030** [comment]
I do not have to copy the Application.java for example?
