### ISSUE TITLE
Play 2.6 support

### ISSUE THREAD

**Issue by KadekM** [joscha/play-authenticate#343]
https://www.playframework.com/documentation/2.6.x/Migration26

**Comment by ernani** [comment]
Also willing to find out when this will be released!

**Comment by ndimas** [comment]
Me too! Can I try to fork this project and try updating the transient dependencies?
It seems to need these three:

**com.typesafe.play:play-logback**_2.11:2.6.2 is selected over {2.5.1, 2.6.0}
[warn]      +- be.objectify:deadbolt-java_2.11:2.6.1              (depends on 2.6.0)
[warn]      +- com.feth:play-authenticate_2.11:0.8.1              (depends on 2.5.1)
[warn]      +- com.feth:play-easymail_2.11:0.8.1                  (depends on 2.5.1)

[warn]  *** com.typesafe.play:play-server**_2.11:2.6.2 is selected over {2.5.1, 2.6.0}
[warn]      +- com.typesafe.play:play-akka-http-server_2.11:2.6.2 (depends on 2.6.2)
[warn]      +- be.objectify:deadbolt-java_2.11:2.6.1              (depends on 2.6.0)
[warn]      +- com.feth:play-authenticate_2.11:0.8.1              (depends on 2.5.1)

[warn]
[warn]  * **com.typesafe.play:twirl-api**_2.11:1.3.3 is selected over {1.1.1, 1.3.2}
[warn]      +- com.typesafe.play:play_2.11:2.6.2                  (depends on 1.3.3)
[warn]      +- be.objectify:deadbolt-java_2.11:2.6.1              (depends on 1.3.2)
[warn]      +- com.feth:play-authenticate_2.11:0.8.1              (depends on 1.1.1)

**Comment by GBeushausen** [comment]
Is this project dead?

**Comment by joscha** [comment]
Not dead, but I am maintaining it with contributions, e.g. I am not actively implementing new features. If you miss a feature, feel free to open a PR with tests.

**Comment by GBeushausen** [comment]
Ah Ok. I'm using this project on two commercial tools and it would be great to be able to upgrade to play 2.6.

**Comment by joscha** [comment]
#345 is almost ready to be merged and released, there are some small adaptions missing.

**Comment by GBeushausen** [comment]
Great. Thanks.

**Comment by source-nerd** [comment]
Any further news on 2.6 build ? Eagerly waiting for it.

**Comment by leccyril** [comment]
+1

**Comment by playtowork** [comment]
+1

**Comment by joscha** [comment]
blocked on deadbolt, see #345, will lock this conversation for now, please comment on #345 if you want to help.
