### ISSUE TITLE
Sign up does not send any email

### ISSUE THREAD

**Issue by Hawk707** [joscha/play-authenticate#355]
Hello,

I cloned the project locally, and ran play-authenticate-usage app. When I try to sign up, I get the 'email sent for verification ... ' response. No exceptions or errors appear. However, I do not receive any email. I am not sure how to debug this. But I used the exact confs in your sample (except in smtp.conf I replaced user with my gmail account, and password with my gmail account password). Do I need to change something else, or what do I need to check to fix this issue? 

Best regards,

**Comment by joscha** [comment]
Did you remove the `mock=true` setting?

**Comment by Hawk707** [comment]
I completely missed that out. Thanks a lot, and happy 2018 to you :)

**Comment by joscha** [comment]
:thumbsup:
