### ISSUE TITLE
Play 2.5 link is not working

### ISSUE THREAD

**Issue by gkovbasenko** [joscha/play-authenticate#371]
Hi!

What happened with branch to support Play 2.5?

**Comment by joscha** [comment]
2.5 support should be in https://github.com/joscha/play-authenticate/tree/2.5.x - there are also released artifacts.

**Comment by gkovbasenko** [comment]
I'm receiving 404 error. Could you please check.

**Comment by joscha** [comment]
you are correct 😱 . I can't see where it went. The last version for 2.5 is 0.8.3 - https://github.com/joscha/play-authenticate/tree/v0.8.3 so you can branch from there if you need to make updates.

**Comment by gkovbasenko** [comment]
Thank you :)
