### ISSUE TITLE
Connection leakage on TokenAction#deleteByUser

### ISSUE THREAD

**Issue by ghost** [joscha/play-authenticate#87]
I found that under high load JDBC connection pool gets exhausted quickly. The change that helped calls QueryIterator#close in the body of TokenAction#deleteByUser as follows:

```
    QueryIterator<TokenAction> iterator = find.where()
            .eq("targetUser.id", u.id).eq("type", type).findIterate();
    Ebean.delete(iterator);
    iterator.close();
```

Nailed down and tested with BoneCP Connection Watch.

Thanks for the good work!
Alex

**Comment by foxmike** [comment]
i am getting
[IllegalArgumentException: Was expecting an EntityBean but got a class com.avaje.ebeaninternal.server.query.CQueryIteratorSimple]
on the
Ebean.delete(iterator);
